import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
import QueryProvider from "@/hooks/utils/QueryProvider";
import Providers from "./providers";
import Script from "next/script";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Workspace",
  description: "Generated by create next app",
  openGraph: {
    title: "Prity",
    description: "Comfortable and Extraordinary",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>


        <Providers>

          <QueryProvider>
            <Toaster position="top-right" richColors />
            <Navbar />
            {/* Load Razorpay Script */}
            <Script
              src="https://checkout.razorpay.com/v1/checkout.js"
              strategy="afterInteractive"
              async
            />
            {children}

            <Footer />
          </QueryProvider>
        </Providers>
      </body>
    </html>
  );
}
